:build :
  :encrypt:
    :dir: gpg
    :suffix: .gpg
  :wiki:
    :dir: wiki
    :suffix: .wiki
  :src:
    :dir: 'src'
    :index: index
    :img: '_image'
  :output:
    :dir: 'githubwiki/fullarts/_posts'
  :template: template

:types:
  :mm: .mm
  :twi: .twi
  :tmd: .tmd
  :wiki: .wiki
  :md: .md
  :html: .html
  :imgs:
    # To protect the use use the link with the type
    - ""
    - .jpg
    - .jepg
    - .png
    - .gif
