:build :
  :encrypt:
    :dir: gpg
    :suffix: .gpg
  :wiki:
    :dir: wiki
    :suffix: .wiki
  :src:
    :dir: 'src'
    :index: index
  :template: template

:types:
  :mm: .mm
  :twi: .twi
  :wiki: .wiki
