:build :
  :encrypt:
    :dir: gpg
    :suffix: .gpg
  :res:
    :dir: __res
  :wiki:
    :dir: wiki
    :suffix: .wiki
  :src:
    :dir: 'src'
    :index: index
    :img: '_image'
  :output:
    :dir: 'githubwiki/www/_posts'
    :img_dir_base: 'githubwiki/www/images'
    :img_prefix: 'https://github.com/qianjigui/www/raw/gh-pages/images'
  :template: template

:types:
  :mm: .mm
  :twi: .twi
  :tmd: .tmd
  :wiki: .wiki
  :md: .md
  :html: .html
  :imgs:
    # To protect the use use the link with the type
    - ""
    - .jpg
    - .jepg
    - .png
    - .gif
